import AppShell from "@/components/AppShell";
import AuthGate from "@/components/AuthGate";
import { StampVisual } from "@/components/StampVisual";
import { getStamp } from "@/data/catalog";
import { useCollectionDemo } from "@/contexts/CollectionDemoContext";
import { ArrowDown, ArrowUp, Check, FolderPlus, Image, Plus, Sparkles } from "lucide-react";
import { FormEvent, useState } from "react";

export default function Albums() { return <AppShell><AuthGate title="Shape your albums"><AlbumsContent /></AuthGate></AppShell>; }

function AlbumsContent() {
  const { albums, items, isLoading, assignItem, createAlbum, moveAlbumItem, setAlbumCover } = useCollectionDemo();
  const [selectedId, setSelectedId] = useState(albums[0]?.id ?? "");
  const [showCreate, setShowCreate] = useState(false);
  const selected = albums.find((album) => album.id === selectedId) ?? albums[0];
  const selectedItems = selected?.itemIds.map((id) => items.find((item) => item.id === id)).filter(Boolean) ?? [];
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); createAlbum(String(form.get("name") || ""), String(form.get("description") || "")); event.currentTarget.reset(); setShowCreate(false); }
  return <main className="container py-10 sm:py-14"><div className="flex flex-col justify-between gap-6 lg:flex-row lg:items-end"><div><p className="eyebrow">Album organiser</p><h1 className="mt-4 font-display text-5xl font-semibold tracking-[-.06em] text-[#173a34] sm:text-6xl">Arrange the collection.</h1><p className="mt-4 max-w-2xl text-base leading-7 text-[#53685d]">Create named albums, assign any saved stamp, choose the cover record, and order items in a focused presentation.</p></div><button onClick={() => setShowCreate((visible) => !visible)} className="inline-flex items-center gap-2 self-start rounded-full bg-[#173a34] px-4 py-2.5 text-sm font-semibold text-white transition hover:bg-[#28574d]"><FolderPlus size={16} /> New album</button></div>
    {showCreate ? <form onSubmit={submit} className="mt-8 grid gap-3 rounded-[1.35rem] border border-[#173a34]/10 bg-white p-5 sm:grid-cols-[1fr_1fr_auto] sm:items-end"><label className="text-sm font-semibold text-[#365746]">Album name<input required name="name" placeholder="e.g. Postwar design" className="mt-2 h-11 w-full rounded-xl border border-[#173a34]/10 px-3 font-normal outline-none focus:border-[#5d887a]" /></label><label className="text-sm font-semibold text-[#365746]">Short description<input name="description" placeholder="What belongs here?" className="mt-2 h-11 w-full rounded-xl border border-[#173a34]/10 px-3 font-normal outline-none focus:border-[#5d887a]" /></label><button className="h-11 rounded-xl bg-[#e8c56f] px-4 text-sm font-bold text-[#214031]">Create album</button></form> : null}
    {isLoading ? <div className="mt-9 grid min-h-[350px] place-items-center rounded-[1.5rem] border border-[#173a34]/10 bg-white/70 text-sm font-semibold text-[#557165]">Loading your authenticated albums…</div> : <section className="mt-9 grid gap-6 xl:grid-cols-[300px_1fr]"><aside className="space-y-3">{albums.map((album) => { const cover = getStamp(album.coverStampSlug); return <button key={album.id} onClick={() => setSelectedId(album.id)} className={`flex w-full items-center gap-3 rounded-2xl border p-3 text-left transition ${selected?.id === album.id ? "border-[#4e826b] bg-[#e7f0e7] shadow-sm" : "border-[#173a34]/10 bg-white/75 hover:bg-white"}`}><div className="grid h-14 w-12 shrink-0 place-items-center overflow-hidden rounded-lg bg-[#dfe9df] p-1.5">{cover ? <StampVisual stamp={cover} className="h-[47px] w-[37px]" showPerforation={false} /> : <Image size={16} />}</div><div className="min-w-0"><p className="truncate font-display text-xl font-semibold text-[#1d4033]">{album.name}</p><p className="mt-1 text-xs text-[#62766b]">{album.itemIds.length} stamps</p></div></button>; })}</aside>
      {selected ? <div className="rounded-[1.6rem] border border-[#173a34]/10 bg-white/80 p-5 sm:p-7"><div className="flex flex-col justify-between gap-5 sm:flex-row"><div><p className="eyebrow">Editing album</p><h2 className="mt-2 font-display text-4xl font-semibold tracking-[-.05em] text-[#173a34]">{selected.name}</h2><p className="mt-3 max-w-xl text-sm leading-6 text-[#60756a]">{selected.description}</p></div><div className="rounded-xl bg-[#edf3ed] px-4 py-3 text-sm text-[#426653]"><span className="font-semibold">Cover:</span> {getStamp(selected.coverStampSlug)?.title || "Not set"}</div></div>
        <div className="mt-8 grid gap-4 md:grid-cols-2">{selectedItems.length ? selectedItems.map((item, index) => { if (!item) return null; const stamp = getStamp(item.stampSlug); if (!stamp) return null; return <div key={item.id} className="flex gap-4 rounded-2xl border border-[#173a34]/10 bg-[#fbfcf9] p-3"><div className="grid h-[105px] w-[80px] shrink-0 place-items-center rounded-xl bg-[#e5ece3] p-2"><StampVisual stamp={stamp} className="h-[87px] w-[68px]" showPerforation={false} /></div><div className="flex min-w-0 flex-1 flex-col"><p className="text-[10px] font-bold uppercase tracking-[.13em] text-[#73857a]">Position {String(index + 1).padStart(2, "0")}</p><h3 className="mt-1 font-display text-xl font-semibold text-[#214637]">{stamp.title}</h3><p className="mt-1 text-xs text-[#6e8076]">{stamp.country} · {stamp.year}</p><div className="mt-auto flex items-center gap-2 pt-3"><button onClick={() => moveAlbumItem(selected.id, item.id, -1)} disabled={index === 0} className="grid h-8 w-8 place-items-center rounded-full border border-[#173a34]/10 text-[#456859] disabled:opacity-30" aria-label="Move stamp earlier"><ArrowUp size={14} /></button><button onClick={() => moveAlbumItem(selected.id, item.id, 1)} disabled={index === selectedItems.length - 1} className="grid h-8 w-8 place-items-center rounded-full border border-[#173a34]/10 text-[#456859] disabled:opacity-30" aria-label="Move stamp later"><ArrowDown size={14} /></button><button onClick={() => setAlbumCover(selected.id, stamp.slug)} className="ml-auto inline-flex items-center gap-1.5 text-xs font-semibold text-[#315f4a] hover:underline"><Sparkles size={13} /> Set cover</button></div></div></div>; }) : <div className="grid min-h-[220px] place-items-center rounded-2xl border border-dashed border-[#86a896]/40 bg-[#edf3ed] p-6 text-center md:col-span-2"><div><span className="mx-auto grid h-10 w-10 place-items-center rounded-full bg-white text-[#4b7b64]"><Plus size={18} /></span><p className="mt-3 font-semibold text-[#315744]">This album is ready for its first stamp.</p><p className="mt-1 text-sm text-[#687b70]">Use the assignment list below to bring a record in.</p></div></div>}</div>
        <div className="mt-8 border-t border-[#173a34]/10 pt-6"><div className="flex items-center gap-2"><Check size={16} className="text-[#5a8b71]" /><h3 className="font-display text-2xl font-semibold text-[#224837]">Assign saved stamps</h3></div><div className="mt-4 grid gap-2">{items.map((item) => { const stamp = getStamp(item.stampSlug); if (!stamp) return null; const assignedTo = albums.find((album) => album.itemIds.includes(item.id)); return <div key={item.id} className="flex flex-col gap-3 rounded-xl bg-[#f3f6f1] px-3 py-3 sm:flex-row sm:items-center"><div className="flex flex-1 items-center gap-3"><StampVisual stamp={stamp} className="h-11 w-9" showPerforation={false} /><span className="text-sm font-semibold text-[#2c4e3e]">{stamp.title}</span></div><select value={assignedTo?.id ?? "unfiled"} onChange={(event) => assignItem(item.id, event.target.value === "unfiled" ? null : event.target.value)} className="rounded-lg border border-[#173a34]/10 bg-white px-2 py-2 text-sm text-[#355846]"><option value="unfiled">Not in an album</option>{albums.map((album) => <option key={album.id} value={album.id}>{album.name}</option>)}</select></div>; })}</div></div>
      </div> : null}</section>}
  </main>;
}
