import AppShell from "@/components/AppShell";
import { trpc } from "@/lib/trpc";
import { BookOpen, LoaderCircle } from "lucide-react";
import React, { useEffect, useMemo } from "react";
import { Link } from "wouter";

export default function Blog() {
  const articles = trpc.blog.list.useQuery();
  useEffect(() => { document.title = "Stamp Collecting Guides & Research | StampAtlas"; }, []);
  const grouped = useMemo(() => Array.from((articles.data ?? []).reduce((map, article) => { const entries = map.get(article.cluster) ?? []; entries.push(article); map.set(article.cluster, entries); return map; }, new Map<string, NonNullable<typeof articles.data>>()).entries()), [articles.data]);
  return <AppShell><main><section className="border-b border-[#173a34]/10 bg-[#e9eee6]"><div className="container py-14 sm:py-20"><p className="eyebrow"><BookOpen size={14} /> StampAtlas journal</p><h1 className="mt-4 max-w-3xl font-display text-5xl font-semibold tracking-[-.06em] text-[#173a34] sm:text-6xl">Research-led notes for thoughtful collectors.</h1><p className="mt-5 max-w-2xl text-base leading-7 text-[#54695e]">Original guides on collecting, research and preservation. Articles are published only after editorial review and cite their supporting sources.</p></div></section><section className="container py-12 sm:py-16">{articles.isLoading ? <div className="flex items-center gap-2 text-sm text-[#63756a]"><LoaderCircle size={16} className="animate-spin" /> Loading published articles…</div> : null}{articles.error ? <p className="rounded-2xl border border-[#a24d42]/20 bg-[#fff5f1] p-5 text-sm text-[#80372f]">Published articles are temporarily unavailable. Please try again later.</p> : null}{!articles.isLoading && !articles.error && !articles.data?.length ? <div className="rounded-3xl border border-dashed border-[#173a34]/15 bg-white/70 p-8"><h2 className="font-display text-3xl font-semibold">The journal is in editorial review.</h2><p className="mt-3 max-w-xl text-sm leading-6 text-[#63756a]">New original StampAtlas articles will appear here only after their sources and editorial status are reviewed.</p><Link href="/guides/storage-basics" className="mt-5 inline-flex text-sm font-semibold text-[#315746] hover:underline">Read a current collecting guide</Link></div> : null}{grouped.map(([cluster, entries]) => <section key={cluster} className="mb-12"><p className="eyebrow">{cluster}</p><div className="mt-5 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{entries.map((article) => <Link href={`/blog/${article.slug}`} key={article.id} className="catalogue-card group p-6"><p className="text-[11px] font-bold uppercase tracking-[.12em] text-[#698176]">Original StampAtlas guide</p><h2 className="mt-3 font-display text-2xl font-semibold leading-tight text-[#173a34] transition group-hover:text-[#315746]">{article.title}</h2><p className="mt-3 text-sm leading-6 text-[#63756a]">{article.summary}</p><span className="mt-5 inline-flex text-sm font-semibold text-[#315746]">Read the guide →</span></Link>)}</div></section>)}</section></main></AppShell>;
}
