import AppShell from "@/components/AppShell";
import AuthGate from "@/components/AuthGate";
import { StampVisual } from "@/components/StampVisual";
import { getStamp } from "@/data/catalog";
import { useCollectionDemo, type CollectionCondition } from "@/contexts/CollectionDemoContext";
import { useAuth } from "@/_core/hooks/useAuth";
import { Download, Layers3, Plus, Trash2, TrendingUp } from "lucide-react";
import { Link } from "wouter";
import { buildCollectionCsv } from "@/data/collectionLogic";

export default function Dashboard() { return <AppShell><AuthGate title="Your collection is waiting"><DashboardContent /></AuthGate></AppShell>; }

function DashboardContent() {
  const { user } = useAuth();
  const { items, albums, isLoading, removeItem, updateItem } = useCollectionDemo();
  const enriched = items.flatMap((item) => {
    const stamp = getStamp(item.stampSlug);
    return stamp ? [{ item, stamp }] : [];
  });
  const totalValue = enriched.reduce((sum, { item, stamp }) => sum + getEstimate(stamp.value[item.condition === "Used" || item.condition === "Fine used" ? "used" : item.condition === "FDC" ? "fdc" : "mint"]), 0);
  const byCountry = summarise(enriched, ({ stamp }) => stamp.country);
  const byEra = summarise(enriched, ({ stamp }) => stamp.decade);
  function exportCsv() {
    const csv = buildCollectionCsv(enriched.map(({ item, stamp }) => ({ title: stamp.title, country: stamp.country, year: stamp.year, condition: item.condition, purchasePrice: item.purchasePrice, acquiredAt: item.acquiredAt, notes: item.notes })));
    const url = URL.createObjectURL(new Blob([csv], { type: "text/csv" }));
    const anchor = document.createElement("a"); anchor.href = url; anchor.download = "stampatlas-collection.csv"; anchor.click(); URL.revokeObjectURL(url);
  }
  return <main className="container py-10 sm:py-14"><div className="flex flex-col justify-between gap-6 lg:flex-row lg:items-end"><div><p className="eyebrow">Personal collection</p><h1 className="mt-4 font-display text-5xl font-semibold tracking-[-.06em] text-[#173a34] sm:text-6xl">Good to see you, {user?.name?.split(" ")[0] || "collector"}.</h1><p className="mt-4 max-w-2xl text-base leading-7 text-[#53685d]">A private collection workspace. Update your notes, condition, purchase price, and acquisition date from the records below.</p></div><div className="flex flex-wrap gap-3"><button onClick={exportCsv} className="inline-flex items-center gap-2 rounded-full border border-[#173a34]/15 bg-white px-4 py-2.5 text-sm font-semibold text-[#2e5947] transition hover:bg-[#edf3ed]"><Download size={15} /> Export CSV</button><Link href="/explore" className="inline-flex items-center gap-2 rounded-full bg-[#173a34] px-4 py-2.5 text-sm font-semibold text-white transition hover:bg-[#28574d]"><Plus size={15} /> Add a stamp</Link></div></div>
    {isLoading ? <div className="mt-10 grid min-h-[420px] place-items-center rounded-[1.5rem] border border-[#173a34]/10 bg-white/70 text-sm font-semibold text-[#557165]">Loading your authenticated collection…</div> : <>
    <section className="mt-10 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat label="Stamps saved" value={String(items.length)} detail={`${albums.length} active albums`} icon={<Layers3 size={18} />} /><Stat label="Estimated portfolio" value={`$${totalValue}`} detail="Illustrative midpoint" icon={<TrendingUp size={18} />} /><Stat label="Countries represented" value={String(byCountry.length)} detail="Across current items" icon={<span className="font-display text-xl">◎</span>} /><Stat label="Newest addition" value={enriched[0]?.stamp.year.toString() || "—"} detail={enriched[0]?.stamp.title || "No stamps yet"} icon={<span className="font-display text-xl">↗</span>} /></section>
    <section className="mt-10 grid gap-6 xl:grid-cols-[1.2fr_.8fr]"><div className="rounded-[1.5rem] border border-[#173a34]/10 bg-white/80 p-5 sm:p-7"><div className="flex items-end justify-between"><div><p className="eyebrow">Recently added</p><h2 className="mt-2 font-display text-3xl font-semibold tracking-[-.045em]">Your latest records</h2></div><Link href="/albums" className="text-sm font-semibold text-[#315d49] underline underline-offset-4">Organise albums</Link></div><div className="mt-6 overflow-x-auto"><table className="w-full min-w-[700px] text-left"><thead className="border-b border-[#173a34]/10 text-[11px] font-bold uppercase tracking-[.13em] text-[#78887f]"><tr><th className="pb-3">Stamp</th><th className="pb-3">Condition</th><th className="pb-3">Purchase price</th><th className="pb-3">Acquired</th><th className="pb-3"><span className="sr-only">Actions</span></th></tr></thead><tbody>{enriched.map(({ item, stamp }) => <tr key={item.id} className="border-b border-[#173a34]/8 last:border-0"><td className="py-3.5"><div className="flex items-center gap-3"><StampVisual stamp={stamp} className="h-[54px] w-[43px] shrink-0" showPerforation={false} /><div><Link href={`/stamps/${stamp.slug}`} className="font-display text-lg font-semibold text-[#1d4033] hover:underline">{stamp.title}</Link><p className="text-xs text-[#6d7d74]">{stamp.country} · {stamp.year}</p></div></div></td><td className="py-3.5"><select value={item.condition} onChange={(event) => updateItem(item.id, { condition: event.target.value as CollectionCondition })} className="rounded-lg border border-[#173a34]/10 bg-[#fbfcf8] px-2 py-2 text-sm text-[#345647]">{(["Mint", "Fine used", "Used", "FDC"] as const).map((condition) => <option key={condition}>{condition}</option>)}</select></td><td className="py-3.5"><label className="flex w-[96px] items-center rounded-lg border border-[#173a34]/10 bg-[#fbfcf8] px-2 text-sm"><span className="text-[#688075]">$</span><input type="number" min="0" value={item.purchasePrice} onChange={(event) => updateItem(item.id, { purchasePrice: Number(event.target.value) || 0 })} className="w-full bg-transparent px-1 py-2 outline-none" /></label></td><td className="py-3.5"><input type="date" value={item.acquiredAt} onChange={(event) => updateItem(item.id, { acquiredAt: event.target.value })} className="rounded-lg border border-[#173a34]/10 bg-[#fbfcf8] px-2 py-2 text-sm text-[#416152]" /></td><td className="py-3.5 text-right"><button onClick={() => removeItem(item.id)} className="grid h-9 w-9 place-items-center rounded-full text-[#956060] transition hover:bg-[#f9e9e7]" aria-label={`Remove ${stamp.title}`}><Trash2 size={16} /></button></td></tr>)}</tbody></table></div></div>
      <div className="grid gap-6"><Breakdown title="Country breakdown" items={byCountry} /><Breakdown title="Era breakdown" items={byEra} /></div>
    </section>
    <section className="mt-6 rounded-[1.5rem] bg-[#183d34] p-6 text-white sm:p-8"><div className="grid gap-7 lg:grid-cols-[.7fr_1.3fr]"><div><p className="eyebrow text-[#ebcd7e]">Collector&apos;s note</p><h2 className="mt-3 font-display text-3xl font-semibold tracking-[-.045em]">Each entry is yours to annotate.</h2></div><div className="grid gap-3 sm:grid-cols-2">{enriched.slice(0, 2).map(({ item, stamp }) => <label key={item.id} className="rounded-xl bg-white/8 p-4"><span className="text-xs font-semibold text-[#e8cb7e]">{stamp.title}</span><textarea value={item.notes} onChange={(event) => updateItem(item.id, { notes: event.target.value })} className="mt-3 min-h-[70px] w-full resize-none bg-transparent text-sm leading-6 text-[#d4e2d8] outline-none placeholder:text-[#8da69a]" placeholder="Add a collecting note…" /></label>)}</div></div>
    </section>
    </>}
  </main>;
}

function getEstimate(range: [number, number]) { return Math.round((range[0] + range[1]) / 2); }
function summarise<T>(items: T[], selector: (item: T) => string) { const map = new Map<string, number>(); items.forEach((item) => map.set(selector(item), (map.get(selector(item)) || 0) + 1)); return Array.from(map.entries()).map(([label, value]) => ({ label, value })).sort((a, b) => b.value - a.value); }
function Stat({ label, value, detail, icon }: { label: string; value: string; detail: string; icon: React.ReactNode }) { return <div className="rounded-[1.35rem] border border-[#173a34]/10 bg-white/75 p-5"><div className="flex items-center justify-between text-[#527a67]"><span className="text-[11px] font-bold uppercase tracking-[.13em]">{label}</span>{icon}</div><p className="mt-4 font-display text-4xl font-semibold tracking-[-.055em] text-[#183d34]">{value}</p><p className="mt-2 text-sm text-[#6c7e73]">{detail}</p></div>; }
function Breakdown({ title, items }: { title: string; items: { label: string; value: number }[] }) { const max = Math.max(...items.map((item) => item.value), 1); return <div className="rounded-[1.5rem] border border-[#173a34]/10 bg-[#edf3ed] p-6"><h2 className="font-display text-2xl font-semibold tracking-[-.04em] text-[#1f4436]">{title}</h2><div className="mt-5 space-y-4">{items.map((item) => <div key={item.label}><div className="flex justify-between text-sm"><span className="text-[#4c665a]">{item.label}</span><span className="font-semibold text-[#244b3b]">{item.value}</span></div><div className="mt-1.5 h-2 overflow-hidden rounded-full bg-white"><div className="h-full rounded-full bg-[#4e866c]" style={{ width: `${(item.value / max) * 100}%` }} /></div></div>)}</div></div>; }
