import AppShell from "@/components/AppShell";
import { StampVisual } from "@/components/StampVisual";
import { mockIdentificationCandidates } from "@/data/identifyLogic";
import { AlertTriangle, CheckCircle2, FileImage, ImagePlus, LoaderCircle, ScanLine, Sparkles, X } from "lucide-react";
import { ChangeEvent, useEffect, useState } from "react";
import { Link } from "wouter";

export default function Identify() {
  const [preview, setPreview] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [complete, setComplete] = useState(false);

  useEffect(() => () => { if (preview) URL.revokeObjectURL(preview); }, [preview]);
  function chooseFile(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) return; if (!file.type.startsWith("image/")) return; if (preview) URL.revokeObjectURL(preview); setPreview(URL.createObjectURL(file)); setComplete(false); }
  function identify() { if (!preview) return; setLoading(true); window.setTimeout(() => { setLoading(false); setComplete(true); }, 700); }
  const candidates = mockIdentificationCandidates();
  const [primary, ...alternates] = candidates;
  return <AppShell><main className="container py-10 sm:py-14"><div className="mx-auto max-w-3xl text-center"><p className="eyebrow justify-center"><Sparkles size={14} /> Mock identification studio</p><h1 className="mt-4 font-display text-5xl font-semibold tracking-[-.06em] text-[#173a34] sm:text-6xl">A closer look, in seconds.</h1><p className="mx-auto mt-4 max-w-2xl text-base leading-7 text-[#586d62]">Upload a stamp photo to run the demonstration identification flow. The match results are illustrative; they never establish authenticity, value, or a definitive catalogue identification.</p></div>
    <section className="mx-auto mt-10 grid max-w-5xl gap-7 lg:grid-cols-[.9fr_1.1fr]"><div className="rounded-[1.6rem] border border-[#173a34]/10 bg-white/80 p-5 sm:p-7"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-[#667a6e]">1. Add an image</p><h2 className="mt-1 font-display text-2xl font-semibold">Your stamp photo</h2></div>{preview ? <button onClick={() => { if (preview) URL.revokeObjectURL(preview); setPreview(null); setComplete(false); }} className="grid h-9 w-9 place-items-center rounded-full bg-[#edf2ec] text-[#476958]" aria-label="Remove chosen image"><X size={17} /></button> : null}</div><label className="mt-6 grid min-h-[315px] cursor-pointer place-items-center overflow-hidden rounded-2xl border-2 border-dashed border-[#81a693]/50 bg-[#edf3ed] p-6 text-center transition hover:border-[#56816a] hover:bg-[#e8f1e8]">{preview ? <img src={preview} alt="Chosen stamp to identify" className="max-h-[300px] max-w-full rounded-xl object-contain shadow-lg" /> : <div><span className="mx-auto grid h-14 w-14 place-items-center rounded-full bg-white text-[#4d7d65] shadow-sm"><ImagePlus size={22} /></span><p className="mt-4 font-semibold text-[#27493a]">Choose a stamp image</p><p className="mt-2 max-w-[240px] text-sm leading-6 text-[#63776b]">JPEG, PNG, or WebP · local preview only · not uploaded or stored</p></div>}<input type="file" accept="image/jpeg,image/png,image/webp" onChange={chooseFile} className="sr-only" /></label><button disabled={!preview || loading} onClick={identify} className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl bg-[#173a34] px-4 py-3.5 text-sm font-semibold text-white transition hover:bg-[#28574d] disabled:cursor-not-allowed disabled:opacity-40 active:scale-[.98]">{loading ? <><LoaderCircle className="animate-spin" size={17} /> Comparing visual clues…</> : <><ScanLine size={17} /> Find closest match</>}</button><p className="mt-4 flex gap-2 text-xs leading-5 text-[#738278]"><AlertTriangle size={14} className="mt-.5 shrink-0 text-[#a9792c]" />For this MVP, image processing is mock-only and happens in the browser. Do not upload personal or sensitive images.</p></div>
      <div className="rounded-[1.6rem] bg-[#173a34] p-5 text-white sm:p-7"><p className="text-xs font-bold uppercase tracking-[.14em] text-[#eacb80]">2. Likely matches</p>{!complete ? <div className="grid min-h-[420px] place-items-center text-center"><div><span className="mx-auto grid h-14 w-14 place-items-center rounded-full bg-[#254f44] text-[#e9c56d]"><FileImage size={22} /></span><h2 className="mt-5 font-display text-3xl font-semibold">Ready when you are.</h2><p className="mt-3 max-w-sm text-sm leading-6 text-[#bbcec2]">Choose an image and we will reveal a deterministic set of visual candidates with the cues behind the match.</p></div></div> : <div className="mt-5"><div className="rounded-2xl bg-[#f5f7f1] p-4 text-[#173a34]"><div className="flex gap-4"><div className="grid h-[135px] w-[105px] shrink-0 place-items-center rounded-xl bg-[#e3ebe0] p-2"><StampVisual stamp={primary.stamp} className="h-[114px] w-[90px]" showPerforation={false} /></div><div><div className="flex items-center gap-2"><span className="rounded-full bg-[#d9eedb] px-2.5 py-1 text-[10px] font-bold uppercase tracking-[.13em] text-[#317052]">Closest visual match</span></div><h2 className="mt-3 font-display text-2xl font-semibold">{primary.stamp.title}</h2><p className="mt-1 text-sm text-[#607368]">{primary.stamp.country} · {primary.stamp.year}</p><div className="mt-3 flex items-center gap-2"><div className="h-1.5 w-24 overflow-hidden rounded-full bg-[#d5ddd5]"><div className="h-full w-[92%] rounded-full bg-[#4c8b6a]" /></div><span className="text-sm font-bold">{primary.confidence}%</span></div></div></div></div><div className="mt-5"><p className="text-[11px] font-bold uppercase tracking-[.13em] text-[#a9c1b4]">Matching evidence</p><div className="mt-3 grid gap-2">{primary.stamp.distinguishingFeatures.map((feature) => <div key={feature} className="flex items-center gap-2 rounded-xl border border-white/10 bg-white/5 px-3 py-2.5 text-sm text-[#d5e3da]"><CheckCircle2 size={15} className="text-[#e9c56d]" />{feature}</div>)}</div></div><div className="mt-5 grid gap-2 sm:grid-cols-2">{alternates.map((candidate, index) => <Link key={candidate.stamp.id} href={`/stamps/${candidate.stamp.slug}`} className="rounded-xl border border-white/10 bg-white/5 p-3 transition hover:bg-white/10"><p className="text-[10px] font-bold uppercase tracking-[.12em] text-[#e9c56d]">Candidate 0{index + 2}</p><p className="mt-2 font-display text-lg">{candidate.stamp.title}</p><p className="mt-1 text-xs text-[#b6cabe]">{candidate.confidence}% visual confidence</p></Link>)}</div><div className="mt-5 flex flex-wrap gap-3"><Link href={`/stamps/${primary.stamp.slug}`} className="rounded-full bg-[#e8c56f] px-4 py-2.5 text-sm font-semibold text-[#1b4034]">Review record</Link><button onClick={() => setComplete(false)} className="rounded-full border border-white/20 px-4 py-2.5 text-sm font-semibold text-white">No match</button></div></div>}</div></section>
  </main></AppShell>;
}
