import { useAuth } from "@/_core/hooks/useAuth";
import AppShell from "@/components/AppShell";
import { trpc } from "@/lib/trpc";
import { Heart, Image as ImageIcon, LoaderCircle, Sparkles } from "lucide-react";
import { useState } from "react";

export default function Moments() {
  const { user, loading } = useAuth();
  const [favoritesOnly, setFavoritesOnly] = useState(false);
  const moments = trpc.moments.list.useQuery(favoritesOnly ? { favoriteOnly: true } : undefined, { enabled: !!user });
  const toggleFavorite = trpc.moments.toggleFavorite.useMutation({ onSuccess: () => moments.refetch() });

  if (loading) return <div className="grid min-h-screen place-items-center"><LoaderCircle className="animate-spin text-[#426f5a]" /></div>;
  if (!user) return <AppShell><main className="container grid min-h-[65vh] place-items-center py-16"><div className="max-w-lg rounded-[1.75rem] border border-[#173a34]/10 bg-white p-9 text-center shadow-sm"><Sparkles className="mx-auto text-[#b47553]" size={26} /><h1 className="mt-5 font-display text-3xl font-semibold">Your moments, in one place</h1><p className="mt-3 text-sm leading-6 text-[#62746b]">Sign in on the website with the same account you use in the mobile app to see your synchronised life moments.</p></div></main></AppShell>;

  return <AppShell><main className="min-h-screen bg-[#f7f5f0] py-10 dark:bg-[#10231e]"><div className="container"><div className="flex flex-col justify-between gap-5 border-b border-[#173a34]/10 pb-8 md:flex-row md:items-end dark:border-white/10"><div><p className="eyebrow">Life archive</p><h1 className="mt-3 font-display text-4xl font-semibold tracking-[-.055em] text-[#173a34] dark:text-[#eef4ee]">Your moments</h1><p className="mt-3 max-w-xl text-sm leading-6 text-[#60746a] dark:text-[#bcd0c4]">Every saved thought, image and small celebration from the mobile app—available here with the same account.</p></div><button onClick={() => setFavoritesOnly((current) => !current)} className={`inline-flex w-fit items-center gap-2 rounded-full px-4 py-2.5 text-xs font-bold transition ${favoritesOnly ? "bg-[#173a34] text-white" : "border border-[#173a34]/15 bg-white text-[#315746] dark:border-white/15 dark:bg-white/5 dark:text-[#dbe9de]"}`}><Heart size={14} fill={favoritesOnly ? "currentColor" : "none"} /> {favoritesOnly ? "Showing favorites" : "Show favorites"}</button></div>
    {moments.isLoading ? <div className="grid min-h-[45vh] place-items-center"><LoaderCircle className="animate-spin text-[#426f5a]" /></div> : moments.data?.length ? <section className="mt-8 grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{moments.data.map((moment) => { const media = moment.media[0]; const tags = moment.tags.filter((tag): tag is NonNullable<typeof tag> => Boolean(tag)); return <article key={moment.id} className="overflow-hidden rounded-[1.5rem] border border-[#173a34]/10 bg-white shadow-[0_14px_36px_rgba(27,61,48,.06)] dark:border-white/10 dark:bg-white/[.04]">{media ? <img src={media.mediaUrl} alt="" className="h-56 w-full object-cover" /> : <div className="grid h-40 place-items-center bg-[#e8efe7] text-[#6c9380] dark:bg-[#19372e]"><ImageIcon size={25} /></div>}<div className="p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[.12em] text-[#ba7656]">{new Date(moment.occurredAt).toLocaleDateString()}</p><h2 className="mt-2 font-display text-2xl font-semibold text-[#173a34] dark:text-[#edf6ee]">{moment.title}</h2></div><button aria-label={moment.isFavorite ? "Remove favorite" : "Add favorite"} onClick={() => toggleFavorite.mutate({ id: moment.id, isFavorite: !moment.isFavorite })} className="grid h-9 w-9 place-items-center rounded-full bg-[#fff2ed] text-[#c96a55] dark:bg-white/10"><Heart size={16} fill={moment.isFavorite ? "currentColor" : "none"} /></button></div>{moment.note && <p className="mt-3 text-sm leading-6 text-[#61746b] dark:text-[#bfd1c3]">{moment.note}</p>}{tags.length ? <div className="mt-4 flex flex-wrap gap-1.5">{tags.map((tag) => <span key={tag.id} className="rounded-full bg-[#e8f0e7] px-2.5 py-1 text-[11px] font-bold text-[#317154] dark:bg-white/10 dark:text-[#a6d0b1]">#{tag.name}</span>)}</div> : null}{moment.locationLabel && <p className="mt-4 text-xs font-semibold text-[#718279] dark:text-[#aabeb0]">{moment.locationLabel}</p>}</div></article>; })}</section> : <div className="mt-8 rounded-[1.75rem] border border-dashed border-[#173a34]/20 px-6 py-20 text-center dark:border-white/20"><Sparkles className="mx-auto text-[#b47553]" size={26} /><h2 className="mt-4 font-display text-2xl font-semibold text-[#173a34] dark:text-[#edf6ee]">Your archive is ready</h2><p className="mx-auto mt-3 max-w-md text-sm leading-6 text-[#64776d] dark:text-[#bfd0c2]">Use the mobile app to create your first moment, then sync it here whenever you are ready.</p></div>}</div></main></AppShell>;
}
