import AppShell from "@/components/AppShell";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { CheckCircle2, Clock3, SearchX, Trash2 } from "lucide-react";
import { Link } from "wouter";
import { useState } from "react";

const labels = { reviewed: "Reviewed", needs_research: "Needs research", dismissed: "Dismissed" } as const;
type ScanStatus = keyof typeof labels;

function ScanCard({ scan }: { scan: { id: number; topCandidateSlug: string | null; candidateSlugs: string; aiAnalysisJson: string | null; model: string | null; status: ScanStatus; note: string | null; createdAt: Date } }) {
  const utils = trpc.useUtils(); const [note, setNote] = useState(scan.note || ""); const [status, setStatus] = useState<ScanStatus>(scan.status);
  const update = trpc.identification.update.useMutation({ onSuccess: () => utils.identification.list.invalidate() });
  const remove = trpc.identification.remove.useMutation({ onSuccess: () => utils.identification.list.invalidate() });
  const candidates = (() => { try { return JSON.parse(scan.candidateSlugs) as string[]; } catch { return []; } })();
  const analysis = (() => { try { return scan.aiAnalysisJson ? JSON.parse(scan.aiAnalysisJson) as { confidence?: number; visualClues?: string[] } : null; } catch { return null; } })();
  return <article className="rounded-2xl border border-[#173a34]/10 bg-white/85 p-5 shadow-[0_10px_28px_rgba(23,58,52,.05)]"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[.13em] text-[#63806f]">{new Date(scan.createdAt).toLocaleString()}</p><h2 className="mt-2 font-display text-2xl font-semibold text-[#173a34]">{scan.topCandidateSlug ? <Link href={`/stamps/${scan.topCandidateSlug}`} className="hover:underline">Candidate: {scan.topCandidateSlug}</Link> : "Candidate set"}</h2></div><div className="flex items-center gap-2"><select value={status} onChange={(event) => { const next = event.target.value as ScanStatus; setStatus(next); update.mutate({ id: scan.id, status: next, note }); }} className="rounded-full border border-[#173a34]/15 bg-[#f7f5f0] px-3 py-2 text-xs font-bold uppercase tracking-[.08em] text-[#355947]">{Object.entries(labels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><button type="button" onClick={() => remove.mutate({ id: scan.id })} disabled={remove.isPending} className="grid h-9 w-9 place-items-center rounded-full text-[#8b5a48] transition hover:bg-[#f8e8e0] disabled:opacity-50" aria-label="Delete private scan" title="Delete private scan"><Trash2 size={16} /></button></div></div><p className="mt-4 text-sm leading-6 text-[#587064]">{candidates.length ? <>Visual candidates: {candidates.map((slug) => <Link key={slug} href={`/stamps/${slug}`} className="font-semibold text-[#2e6750] hover:underline">{slug}</Link>).reduce<React.ReactNode[]>((parts, node, index) => index ? [...parts, ", ", node] : [node], [])}</> : "No candidate slugs were retained."}</p>{analysis ? <div className="mt-4 rounded-xl bg-[#edf4ed] p-3 text-sm text-[#365947]"><p className="font-semibold">AI visual review{typeof analysis.confidence === "number" ? ` · ${analysis.confidence}% similarity` : ""}</p>{analysis.visualClues?.length ? <p className="mt-1 leading-6">{analysis.visualClues.join(" · ")}</p> : null}{scan.model ? <p className="mt-1 text-xs text-[#668273]">Model: {scan.model}</p> : null}</div> : null}<label className="mt-4 block"><span className="sr-only">Private research note</span><Input value={note} onChange={(event) => setNote(event.target.value)} onBlur={() => { if (note !== (scan.note || "")) update.mutate({ id: scan.id, status, note: note || null }); }} placeholder="Add a private research note" className="border-[#173a34]/15 bg-[#f7f5f0]" /></label></article>;
}

export default function ScanHistory() { const { data, isLoading } = trpc.identification.list.useQuery(); return <AppShell><main className="container max-w-5xl py-10 sm:py-14"><header className="flex flex-wrap items-end justify-between gap-5"><div><p className="eyebrow"><Clock3 size={14} /> Private research log</p><h1 className="mt-4 font-display text-5xl font-semibold tracking-[-.06em] text-[#173a34]">My identification history</h1><p className="mt-4 max-w-2xl text-base leading-7 text-[#5d7368]">Each saved entry keeps visual candidate slugs, your research status and a private note. Uploaded source images are never retained.</p></div><Link href="/identify"><Button className="rounded-full bg-[#173a34]">New identification</Button></Link></header>{isLoading ? <div className="mt-10 grid gap-4"><div className="h-40 animate-pulse rounded-2xl bg-[#e9eee6]" /><div className="h-40 animate-pulse rounded-2xl bg-[#e9eee6]" /></div> : data?.length ? <section className="mt-10 grid gap-4">{data.map((scan) => <ScanCard key={scan.id} scan={scan} />)}</section> : <section className="mt-10 rounded-[1.6rem] border border-dashed border-[#6f9581]/50 bg-[#eef4ed] px-6 py-14 text-center"><SearchX className="mx-auto text-[#5a826d]" /><h2 className="mt-4 font-display text-3xl font-semibold text-[#173a34]">No saved scans yet</h2><p className="mx-auto mt-3 max-w-md text-sm leading-6 text-[#5c7568]">Run the mock identification flow while signed in to start a private research log.</p></section>}<aside className="mt-9 flex gap-3 rounded-2xl border border-[#d9c176]/45 bg-[#fff9e8] p-4 text-sm leading-6 text-[#705b2c]"><CheckCircle2 className="mt-0.5 shrink-0" size={17} />Statuses are personal workflow markers, not authenticity assessments or appraisals.</aside></main></AppShell>; }
