import AppShell from "@/components/AppShell";
import { StampVisual } from "@/components/StampVisual";
import { getStamp } from "@/data/catalog";
import { startLogin } from "@/const";
import { useCollectionDemo } from "@/contexts/CollectionDemoContext";
import { useAuth } from "@/_core/hooks/useAuth";
import { AlertCircle, ArrowLeft, BookOpen, Check, ExternalLink, Landmark, Plus, ShieldCheck } from "lucide-react";
import { Link, useLocation, useRoute } from "wouter";

export default function StampDetail() {
  const [, params] = useRoute("/stamps/:slug");
  const { user } = useAuth();
  const { addStamp } = useCollectionDemo();
  const [, setLocation] = useLocation();
  const stamp = getStamp(params?.slug ?? "");
  if (!stamp) return <AppShell><main className="container grid min-h-[58vh] place-items-center py-16 text-center"><div><p className="eyebrow justify-center">Record unavailable</p><h1 className="mt-4 font-display text-4xl font-semibold">This catalogue entry is not available.</h1><Link href="/explore" className="mt-6 inline-flex items-center gap-2 text-sm font-semibold text-[#285847]"><ArrowLeft size={15} /> Back to the catalogue</Link></div></main></AppShell>;

  function saveToCollection() { if (!stamp) return; if (!user) { startLogin(); return; } addStamp(stamp.slug); setLocation("/dashboard"); }
  return <AppShell><main className="container py-8 sm:py-12">
    <nav className="flex items-center gap-2 text-sm text-[#63766b]" aria-label="Breadcrumb"><Link href="/explore" className="hover:text-[#173a34]">Catalogue</Link><span>/</span><span>{stamp.country}</span><span>/</span><span className="text-[#294a3d]">{stamp.title}</span></nav>
    <section className="mt-7 grid gap-10 lg:grid-cols-[minmax(360px,.86fr)_minmax(0,1.14fr)]">
      <div className="relative grid min-h-[470px] place-items-center overflow-hidden rounded-[1.7rem] bg-[#e3ebe0] p-12"><div className="absolute inset-0 opacity-50 [background-image:radial-gradient(#79958a_1px,transparent_1px)] [background-size:14px_14px]" /><StampVisual stamp={stamp} className="relative z-10 h-[370px] w-[292px] shadow-[0_28px_35px_rgba(25,54,42,.18)]" /><span className="absolute bottom-5 left-5 rounded-full bg-white/85 px-3 py-1.5 text-[11px] font-semibold uppercase tracking-[.13em] text-[#3c5c4c]">Seeded demo record</span></div>
      <article className="pt-2"><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-[#e5f0e6] px-3 py-1 text-[11px] font-bold uppercase tracking-[.13em] text-[#3b7158]">{stamp.country}</span><span className="text-sm text-[#63766b]">{stamp.year} · {stamp.denomination}</span></div><h1 className="mt-4 font-display text-5xl font-semibold tracking-[-.06em] text-[#173a34] sm:text-6xl">{stamp.title}</h1><p className="mt-5 max-w-2xl text-base leading-7 text-[#53685d]">{stamp.description}</p><div className="mt-7 flex flex-wrap gap-3"><button onClick={saveToCollection} className="inline-flex items-center gap-2 rounded-full bg-[#173a34] px-5 py-3 text-sm font-semibold text-white transition hover:bg-[#28574d] active:scale-[.97]"><Plus size={16} /> Add to my collection</button><Link href="/identify" className="inline-flex items-center gap-2 rounded-full border border-[#173a34]/15 bg-white px-5 py-3 text-sm font-semibold text-[#274a3c] transition hover:bg-[#edf3ed]"><Check size={16} /> Compare a photo</Link></div>
        <dl className="mt-10 grid gap-x-8 gap-y-5 border-y border-[#173a34]/10 py-7 sm:grid-cols-2"><Meta label="Series" value={stamp.series} /><Meta label="Colour" value={stamp.color} /><Meta label="Perforation" value={stamp.perforation} /><Meta label="Watermark" value={stamp.watermark} /><Meta label="Printing" value={stamp.printingMethod} /><Meta label="Print run" value={stamp.printRun} /></dl>
      </article>
    </section>

    <section className="mt-14 grid gap-7 lg:grid-cols-[1.15fr_.85fr]">
      <div className="rounded-[1.5rem] border border-[#173a34]/10 bg-white/80 p-6 sm:p-8"><div className="flex items-start justify-between gap-4"><div><p className="eyebrow"><Landmark size={14} /> Evidence-led value panel</p><h2 className="mt-3 font-display text-3xl font-semibold tracking-[-.045em]">Condition changes the story.</h2></div><span className="rounded-full bg-[#fbefce] px-3 py-1.5 text-[11px] font-bold uppercase tracking-[.12em] text-[#8a5e1e]">Illustrative</span></div><p className="mt-4 max-w-2xl text-sm leading-6 text-[#60746a]">These mock ranges separate collecting conditions and are not a professional appraisal. They are seeded interface data only and are not based on marketplace or proprietary catalogue data.</p><div className="mt-7 grid gap-3 sm:grid-cols-3"><ValueRange label="Mint" range={stamp.value.mint} tone="bg-[#e6f1e5]" /><ValueRange label="Used" range={stamp.value.used} tone="bg-[#edf0ea]" /><ValueRange label="FDC" range={stamp.value.fdc} tone="bg-[#f9edcf]" /></div><div className="mt-7 border-t border-[#173a34]/10 pt-5"><p className="text-xs font-bold uppercase tracking-[.13em] text-[#65766e]">Value evidence citations</p><div className="mt-3 grid gap-2">{stamp.valueEvidence.map((evidence) => <div key={evidence.condition} className="flex flex-col gap-1 rounded-xl bg-[#f2f5f0] px-3 py-2.5 text-xs leading-5 text-[#556b60] sm:flex-row sm:items-center sm:justify-between"><span><strong className="text-[#284c3d]">{evidence.condition}</strong> · {evidence.observation}</span><span className="font-semibold text-[#647b6e]">{evidence.source} · {evidence.observedAt}</span></div>)}</div><p className="mt-3 text-xs leading-5 text-[#61756a]">0 verified observations · Last updated in development seed · Confidence: {stamp.value.confidence}.</p></div></div>
      <aside className="rounded-[1.5rem] bg-[#183d34] p-6 text-white sm:p-8"><p className="eyebrow text-[#e7bf65]"><ShieldCheck size={14} /> Catalogue discipline</p><h2 className="mt-3 font-display text-3xl font-semibold tracking-[-.045em]">Read the evidence, not one number.</h2><div className="mt-6 space-y-4 text-sm leading-6 text-[#c5d7cb]"><p><strong className="text-white">Mint</strong> means unused with original gum, where relevant. <strong className="text-white">Used</strong> records show postal cancellation or handling. <strong className="text-white">FDC</strong> refers to a first-day cover.</p><p>Condition grading should also account for centring, gum, paper, perforations, cancellation, and repairs.</p></div><a href={stamp.sourceUrl} target="_blank" rel="noreferrer" className="mt-7 inline-flex items-center gap-2 text-sm font-semibold text-[#f3ce7d] underline underline-offset-4">Image source and credit <ExternalLink size={14} /></a></aside>
    </section>
    <section className="mt-10 grid gap-6 rounded-[1.5rem] border border-[#173a34]/10 bg-[#edf3ed] p-6 sm:grid-cols-[auto_1fr] sm:p-8"><div className="grid h-11 w-11 place-items-center rounded-full bg-white text-[#41775f]"><BookOpen size={19} /></div><div><h2 className="font-display text-2xl font-semibold tracking-[-.04em]">Identification notes</h2><p className="mt-2 text-sm leading-6 text-[#566b60]">Use the following details to distinguish this mock record from visually adjacent designs.</p><div className="mt-4 flex flex-wrap gap-2">{stamp.distinguishingFeatures.map((feature) => <span key={feature} className="rounded-full border border-[#6c9680]/30 bg-white px-3 py-1.5 text-sm text-[#355c49]">{feature}</span>)}</div><div className="mt-6 flex items-start gap-2 text-xs leading-5 text-[#64786d]"><AlertCircle size={15} className="mt-.5 shrink-0" />{stamp.catalogueReference}</div></div>
    </section>
  </main></AppShell>;
}

function Meta({ label, value }: { label: string; value: string }) { return <div><dt className="text-[11px] font-bold uppercase tracking-[.13em] text-[#74847b]">{label}</dt><dd className="mt-1 text-sm font-medium leading-5 text-[#2b4d3e]">{value}</dd></div>; }
function ValueRange({ label, range, tone }: { label: string; range: [number, number]; tone: string }) { return <div className={`rounded-2xl p-4 ${tone}`}><p className="text-[11px] font-bold uppercase tracking-[.13em] text-[#5d7167]">{label}</p><p className="mt-2 font-display text-2xl font-semibold text-[#193f33]">${range[0]}–${range[1]}</p><p className="mt-1 text-xs text-[#63786d]">USD range</p></div>; }
