import { previewCollectionCsv, type CsvImportPreview } from "@/data/collectionLogic";
import { trpc } from "@/lib/trpc";
import { Download, FileUp, ShieldCheck } from "lucide-react";
import { useState } from "react";

export function CollectionDataTools() {
  const utils = trpc.useUtils();
  const [preview, setPreview] = useState<CsvImportPreview | null>(null);
  const [filename, setFilename] = useState("");
  const importMutation = trpc.collection.importCsv.useMutation({ onSuccess: () => { void utils.collection.list.invalidate(); void utils.albums.list.invalidate(); } });
  const backupQuery = trpc.collection.backup.useQuery(undefined, { enabled: false });
  function selectFile(file: File | undefined) { if (!file) return; if (!file.name.toLowerCase().endsWith(".csv") || file.size > 2 * 1024 * 1024) { setPreview({ rows: [], errors: [{ row: 0, message: "Choose a CSV file no larger than 2MB" }] }); return; } const reader = new FileReader(); reader.onload = () => { setFilename(file.name); setPreview(previewCollectionCsv(String(reader.result || ""))); }; reader.readAsText(file); }
  async function downloadBackup() { const result = await backupQuery.refetch(); if (!result.data) return; const url = URL.createObjectURL(new Blob([JSON.stringify(result.data, null, 2)], { type: "application/json" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `stampatlas-backup-${new Date().toISOString().slice(0, 10)}.json`; anchor.click(); URL.revokeObjectURL(url); }
  async function importRows() { if (!preview?.rows.length || preview.errors.length || !window.confirm(`Import ${preview.rows.length} validated record(s)? Existing stamp slugs will be skipped.`)) return; await importMutation.mutateAsync({ rows: preview.rows }); setPreview(null); setFilename(""); }
  return <section className="mt-6 grid gap-4 rounded-[1.5rem] border border-[#173a34]/10 bg-[#f5f8f4] p-5 lg:grid-cols-[1fr_auto]"><div><div className="flex items-center gap-2 text-[#315c49]"><FileUp size={17} /><h2 className="font-display text-2xl font-semibold">Import and backup</h2></div><p className="mt-2 max-w-2xl text-sm leading-6 text-[#60756a]">Import a CSV using <strong>Stamp slug</strong>, condition, quantity, status, grade, purchase price, acquired date, storage location, tags and notes. Supported aliases are matched automatically and rows are validated before import.</p><label className="mt-4 inline-flex cursor-pointer items-center gap-2 rounded-full bg-[#173a34] px-4 py-2.5 text-sm font-semibold text-white"><FileUp size={15} /> Choose CSV<input type="file" accept=".csv,text/csv" onChange={(event) => selectFile(event.target.files?.[0])} className="sr-only" /></label>{preview ? <div className={`mt-4 rounded-xl border p-3 text-sm ${preview.errors.length ? "border-[#dba294] bg-[#fff2ee] text-[#843c2d]" : "border-[#9fc4ac] bg-white text-[#315a48]"}`}><div className="flex flex-wrap items-center justify-between gap-2"><span><strong>{filename || "CSV preview"}</strong> · {preview.rows.length} valid row(s) · {preview.errors.length} issue(s)</span>{preview.rows.length && !preview.errors.length ? <button type="button" onClick={importRows} disabled={importMutation.isPending} className="rounded-lg bg-[#e9c46a] px-3 py-1.5 text-xs font-bold text-[#284030] disabled:opacity-50">{importMutation.isPending ? "Importing…" : "Import validated rows"}</button> : null}</div>{preview.errors.slice(0, 4).map((error) => <p key={`${error.row}-${error.message}`} className="mt-1 text-xs">Row {error.row}: {error.message}</p>)}{preview.rows.slice(0, 3).map((row) => <p key={`${row.stampSlug}-${row.acquiredAt}`} className="mt-1 text-xs">{row.stampSlug} · {row.quantity} · {row.collectionStatus}</p>)}</div> : null}{importMutation.data ? <p className="mt-3 text-sm text-[#315a48]"><ShieldCheck size={15} className="mr-1 inline" /> Imported {importMutation.data.createdCount}; skipped {importMutation.data.skippedCount} duplicate slug(s).</p> : null}</div><div className="flex items-start"><button type="button" onClick={downloadBackup} disabled={backupQuery.isFetching} className="inline-flex items-center gap-2 rounded-full border border-[#173a34]/15 bg-white px-4 py-2.5 text-sm font-semibold text-[#315b4a] disabled:opacity-50"><Download size={15} /> {backupQuery.isFetching ? "Preparing…" : "Download JSON backup"}</button></div></section>;
}
